### ISSUE TITLE
Script crashing if IP ban time has been extended

### ISSUE THREAD

**Issue by lyzcoote** [aaron555/fail2ban-analyse#2]
While running the script (either via the .sh or main .py file), it crashes while trying to run `curl ipinfo.io` due to the IP having the text saying that the IP ban time has been extended to 2 x default ban time (1 day in my case)

```
/bin/sh: 1: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "/home/lyz/Gits/fail2ban-analyse/scripts/fail2ban_analyse.py", line 307, in <module>
    attacker_ele = subprocess.check_output("curl ipinfo.io/%s/geo" % line, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'curl ipinfo.io/103.212.211.129 (2 # 2 days, 0:00:00 -> 2023-01-18 18:57:41)/geo' returned non-zero exit status 2.
ERROR: Fail2ban log analysis failed
```

**Comment by aaron555** [comment]
Thanks very much for that, good spot - the IPs were not being extracted properly from the logs. should be fixed now.
