### ISSUE TITLE
Script fail2ban_analyse_wrapper.sh failed with: ValueError: time data 'From: Fail' does not match format '%Y-%m-%d'

### ISSUE THREAD

**Issue by evadim** [aaron555/fail2ban-analyse#4]
Console log:
```
./fail2ban_analyse_wrapper.sh
-------------------------------------------------------------------------------------------
Fail2ban log analysis and visualisation wrapper process started
Attempting to analyse auth/secure logs in /var/log/ to determine usernames of failed ssh attempts...
WARNING: Could not find system logfiles to analyse usernames of failed SSH login attempts, username analysis unavailable
-------------------------------------------------------------------------------------------
2023-10-21_19:02:39: Starting fail2ban log analysis
Using 1 log files in /var/log/
Opening log file /var/log/fail2ban.log
Writing raw logs to 20231021_fail2ban_all_raw_logs.txt
Analysing 3570335 total lines in log
Log covers attacks from 2020-12-27 04:42:43 to 2023-10-21 22:02:08
Writing log of all attack IPs with timestamps to 20231021_fail2ban_attack_IPs_all.csv
Total 49105 attacks from 20944 unique IPs
Top 3 offenders: 1-185.224.249.25 (156); 2-36.110.228.254 (142); 3-116.105.212.31 (126)
Writing log of all UNIQUE attack IPs to 20231021_fail2ban_attack_IPs_unique.csv
These attacks come from 16606 unique subnets (/24)
Top 3 subnets (/24): 1-141.98.11.x (1416); 2-141.98.10.x (1152); 3-221.181.185.x (730)
Writing log of all UNIQUE SUBNETS (assume /24) to 20231021_fail2ban_attack_IPs_unique_subnet.csv
WARNING: usernames.txt file not found - no username analysis possible
Writing summary log 20231021_fail2ban_log_analysis_summary.txt
Importing modules and plotting number of attacks per day on chart
Traceback (most recent call last):
  File "/root/fail2ban-analyse/scripts/fail2ban_analyse.py", line 272, in <module>
    line_day = date2num(DT.datetime.strptime(ele[0:10], "%Y-%m-%d"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'From: Fail' does not match format '%Y-%m-%d'
ERROR: Fail2ban log analysis failed

```
Not sure how to debug further.

part of /tmp/fail2ban-analyse/20231021_fail2ban_all_raw_logs.txt
```
2023-10-21 21:55:49,723 fail2ban.filter         [7162]: INFO    [sshd] Found 114.132.220.22 - 2023-10-21 21:55:49
2023-10-21 21:55:52,808 fail2ban.filter         [7162]: INFO    [sshd] Found 14.116.189.74 - 2023-10-21 21:55:52
2023-10-21 21:56:50,037 fail2ban.filter         [7162]: INFO    [sshd] Found 114.132.220.22 - 2023-10-21 21:56:49
2023-10-21 21:57:03,740 fail2ban.filter         [7162]: INFO    [sshd] Found 14.116.189.74 - 2023-10-21 21:57:03
2023-10-21 21:57:11,619 fail2ban.actions        [7162]: NOTICE  [sshd] Unban 1.116.159.55
2023-10-21 21:59:37,658 fail2ban.actions        [7162]: NOTICE  [sshd] Unban 167.99.70.85
2023-10-21 21:59:55,968 fail2ban.filter         [7162]: INFO    [sshd] Found 14.116.189.74 - 2023-10-21 21:59:55
2023-10-21 21:59:56,269 fail2ban.actions        [7162]: NOTICE  [sshd] Ban 14.116.189.74
2023-10-21 21:59:56,377 fail2ban.filter         [7162]: INFO    [recidive] Found 14.116.189.74 - 2023-10-21 21:59:56
2023-10-21 22:02:07,811 fail2ban.filter         [7162]: INFO    [sshd] Found 114.132.220.22 - 2023-10-21 22:02:07
2023-10-21 22:02:08,544 fail2ban.actions        [7162]: NOTICE  [sshd] Ban 114.132.220.22
2023-10-21 22:02:08,549 fail2ban.filter         [7162]: INFO    [recidive] Found 114.132.220.22 - 2023-10-21 22:02:08
```
OS: Gentoo
SSH log with errors located at /var/log/sshd/current (default Metalog setup)

**Comment by aaron555** [comment]
Please can you send me the output in "20231021_fail2ban_log_analysis_summary.txt" and ideally if possible the original raw log files you are using from /var/log ?

It looks like maybe one of the input log lines doesn't start with YY-MM-DD ? 

I will look in more detail as soon as I can.

Also probably need to recognise different SSH logs for pulling failed username attempts e.g. /var/log/sshd/current as you specify - however this is only a warning and not related to the error.

**Comment by evadim** [comment]
@aaron555 you gave an idea, so I grep log carefully and found some issues, like unsent email for some reason saved in log. After they removed everything works.
Have no idea how they get inside log, I got message per few minutes. Maybe it worth to discard such lines?

Regarding ssh do you need something from me to help you?
```diff
--- /root/fail2ban.log    2023-10-28 02:21:44.000000000 +0300
+++ /var/log/fail2ban.log       2023-10-28 10:13:52.000000000 +0300
@@ -4555,28 +4555,8 @@
 2023-10-26 08:36:02,635 fail2ban.actions        [7162]: NOTICE  [sshd] Ban 154.221.19.48
 2023-10-26 08:36:02,635 fail2ban.filter         [7162]: INFO    [recidive] Found 154.221.19.48 - 2023-10-26 08:36:02
 2023-10-26 08:37:02,649 fail2ban.utils          [7162]: ERROR   7ffa5e2fae30 -- exec: printf %b "Subject: [Fail2Ban] sshd: banned 154.221.19.48 from ***
-Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
-From: Fail2Ban <fail2ban@***>
-To: ***@***\n
-Hi,\n
-The IP 154.221.19.48 has just been banned by Fail2Ban after
-5 attempts against sshd.\n\n
-Here is more information about 154.221.19.48 :\n
-`whois 154.221.19.48 || echo "missing whois program"`\n
-Regards,\n
-Fail2Ban" | /usr/sbin/sendmail -f "fail2ban@***" "***@***"
 2023-10-26 08:37:02,649 fail2ban.utils          [7162]: ERROR   7ffa5e2fae30 -- timed out after 60 seconds.
 2023-10-26 08:37:02,849 fail2ban.utils          [7162]: ERROR   printf %b "Subject: [Fail2Ban] sshd: banned 154.221.19.48 from ***
-Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
-From: Fail2Ban <fail2ban@***>
-To: ***@***\n
-Hi,\n
-The IP 154.221.19.48 has just been banned by Fail2Ban after
-5 attempts against sshd.\n\n
-Here is more information about 154.221.19.48 :\n
-`whois 154.221.19.48 || echo "missing whois program"`\n
-Regards,\n
-Fail2Ban" | /usr/sbin/sendmail -f "fail2ban@***" "***@***" -- failed with [Errno 3] No such process
 2023-10-26 08:37:02,850 fail2ban.utils          [7162]: ERROR   7ffa5e2fae30 -- stderr: 'Задержка.'
 2023-10-26 08:37:02,850 fail2ban.utils          [7162]: ERROR   7ffa5e2fae30 -- killed with SIGTERM (return code: -15)
 2023-10-26 08:44:24,040 fail2ban.filter         [7162]: INFO    [sshd] Found 180.245.1.156 - 2023-10-26 08:44:23
@@ -6406,3 +6386,932 @@
 ```

**Comment by WBeulink** [comment]
I found the same problem today in my new installation of your script.
Same sort of errors I have to say.
But I was able to remove them ....
My fail2ban logs starts each line with a space and then comes the date.
When I remove these spaces everything works!
No idea why this space is present.
